# /home/shaw/.config/tmuxinator/work.yml

name: nucleus
root: /home/shaw/Projects/nucleus

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

# Runs on project start, always
# on_project_start: command

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
# on_project_exit: command

# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:
  - api:
      layout: 897d,426x111,0,0{283x111,0,0[283x87,0,0,17,283x23,0,88,31],142x111,284,0[142x55,284,0,18,142x55,284,56,30]}
      #layout: dd11,426x111,0,0{141x111,0,0,17,141x111,142,0,18,142x111,284,0[142x71,284,0,19,142x39,284,72,20]}
      panes:
        - editor:
          - cd mgmt-api
          - vi
        - cd mgmt-api
        - cd mgmt-api
  - web:
    #layout: dd11,426x111,0,0{141x111,0,0,17,141x111,142,0,18,142x111,284,0[142x71,284,0,19,142x39,284,72,20]}
      layout: 897d,426x111,0,0{283x111,0,0[283x87,0,0,17,283x23,0,88,31],142x111,284,0[142x55,284,0,18,142x55,284,56,30]}
      panes:
        - editor:
          - cd app
          - vi
        - cd app
        - cd app
  - cli:
    #layout: dd11,426x111,0,0{141x111,0,0,17,141x111,142,0,18,142x111,284,0[142x71,284,0,19,142x39,284,72,20]}
      layout: 897d,426x111,0,0{283x111,0,0[283x87,0,0,17,283x23,0,88,31],142x111,284,0[142x55,284,0,18,142x55,284,56,30]}
      panes:
        - cd cli
        - editor:
          - cd cli
          - vi
        - cd cli
  - infra:
    #layout: dd11,426x111,0,0{141x111,0,0,17,141x111,142,0,18,142x111,284,0[142x71,284,0,19,142x39,284,72,20]}
      layout: 897d,426x111,0,0{283x111,0,0[283x87,0,0,17,283x23,0,88,31],142x111,284,0[142x55,284,0,18,142x55,284,56,30]}
      panes:
        - editor:
          - cd kustomize
          - vi
        - cd kustomize
        - cd kustomize
